apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: yo00oy/board:v3
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-service